
services:
  portfolio:
    image: portfolio:latest
    build: .
    volumes:
      - ./:/usr/src/app/
    restart: unless-stopped
    dns:
      - 8.8.8.8
    ports:
      - "8081:8501"
    entrypoint: 
      - /bin/bash
      - -c
      - |
        chmod +x /usr/src/app/scripts/entrypoint.sh || true;
        /usr/src/app/scripts/entrypoint.sh;
        while inotifywait -r -e modify,create,delete,move /usr/src/app; do
          echo 'Change detected, reloading...';
          /usr/src/app/scripts/entrypoint.sh;
        done
